// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQPiN7DLWyhaFfg1mVmGo_KM4JktuPSik',
    appId: '1:346662287423:web:1bac4bc91cf1254465e08a',
    messagingSenderId: '346662287423',
    projectId: 'tummyfull-fbase',
    authDomain: 'tummyfull-fbase.firebaseapp.com',
    storageBucket: 'tummyfull-fbase.appspot.com',
    measurementId: 'G-F80DRFSCK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV6CULDLaLQNYOJLvALEqRPtFDcQrVbFQ',
    appId: '1:346662287423:android:049d424a7f27d39c65e08a',
    messagingSenderId: '346662287423',
    projectId: 'tummyfull-fbase',
    storageBucket: 'tummyfull-fbase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR1f84p-y8pwa2RtN52LU86eM_FiI_sqA',
    appId: '1:346662287423:ios:6d1e926847c1b69465e08a',
    messagingSenderId: '346662287423',
    projectId: 'tummyfull-fbase',
    storageBucket: 'tummyfull-fbase.appspot.com',
    iosBundleId: 'com.example.mealready',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR1f84p-y8pwa2RtN52LU86eM_FiI_sqA',
    appId: '1:346662287423:ios:775381f60cbf70d265e08a',
    messagingSenderId: '346662287423',
    projectId: 'tummyfull-fbase',
    storageBucket: 'tummyfull-fbase.appspot.com',
    iosBundleId: 'com.example.mealready.RunnerTests',
  );
}
